<?php
function PlantSpeciesList() {
  return array(
    array("Acacia spp.", "Acacia spp."),
    array("Maple spp.", "Acer spp."),
    array("Buckeye spp.", "Aesculus spp."),
    array("Ailanthus spp.", "Ailanthus spp."),
    array("Alder spp.", "Alnus spp."),
    array("Madrone spp.", "Arbutus spp."),
    array("Birch spp.", "Betula spp."),
    array("Boxwood spp.", "Buxus spp."),
    array("Sweetshrub spp.", "Calycanthus spp."),
    array("Camellia spp.", "Camellia spp."),
    array("Hornbeam spp.", "Carpinus spp."),
    array("Hickory spp.", "Carya spp."),
    array("Chestnut spp.", "Castanea spp."),
    array("Sheoak spp.", "Casuarina spp."),
    array("Catalpa spp.", "Catalpa spp."),
    array("Hackberry spp.", "Celtis spp."),
    array("Fringetree spp.", "Chionanthus spp."),
    array("Citrus spp.", "Citrus spp."),
    array("Cleyera spp.", "Cleyera spp."),
    array("Dogwood spp.", "Cornus spp."),
    array("Hazelnut spp.", "Corylus spp."),
    array("Hawthorn spp.", "Crataegus spp."),
    array("Bush honeysuckle spp.", "Diervilla spp."),
    array("Persimmon spp.", "Diospyros spp."),
    array("Eucalyptus spp.", "Eucalyptus spp."),
    array("Beech spp.", "Fagus spp."),
    array("Fig spp.", "Ficus spp."),
    array("Forsythia spp.", "Forsythia spp."),
    array("Ash spp.", "Fraxinus spp."),
    array("Gardenia spp.", "Gardenia spp."),
    array("Huckleberry spp.", "Gaylussacia spp."),
    array("Locust spp.", "Gleditsia spp."),
    array("Silverbell spp.", "Halesia spp."),
    array("Hydrangea spp.", "Hydrangea spp."),
    array("Walnut spp.", "Juglans spp."),
    array("Privet spp.", "Ligustrum spp."),
    array("Spicebush spp.", "Lindera spp."),
    array("Honeysuckle spp.", "Lonicera spp."),
    array("Magnolia spp.", "Magnolia spp."),
    array("Apple spp.", "Malus spp."),
    array("Mulberry spp.", "Morus spp."),
    array("Tupelo spp.", "Nyssa spp."),
    array("Tupelo spp.", "Nyssa spp."),
    array("Hophornbeam spp.", "Ostrya spp."),
    array("Bay spp.", "Persea spp."),
    array("Sycamore spp.", "Platanus spp."),
    array("Sycamore spp.", "Platanus spp."),
    array("NA spp.", "Podocarpus spp."),
    array("Cottonwood and poplar spp.", "Populus spp."),
    array("Mesquite spp.", "Prosopis spp."),
    array("Cherry spp.", "Prunus spp."),
    array("Cherry and plum spp.", "Prunus spp."),
    array("Pear spp.", "Pyrus spp."),
    array("Oak spp.", "Quercus spp."),
    array("Buckthorn spp.", "Rhamnus spp."),
    array("Azalea, rhododendron spp.", "Rhododendron spp."),
    array("Sumac spp.", "Rhus spp."),
    array("Rose spp.", "Rosa spp."),
    array("Royal palm spp.", "Roystonea spp."),
    array("Brambles spp.", "Rubus spp."),
    array("Willow spp.", "Salix spp."),
    array("Elderberry spp.", "Sambucus spp."),
    array("Sassafras spp.", "Sassafras spp."),
    array("Mountain-ash spp.", "Sorbus spp."),
    array("Stewartia spp.", "Stewartia spp."),
    array("Lilac spp.", "Syringa spp."),
    array("Saltcedar spp.", "Tamarix spp."),
    array("Basswood spp.", "Tilia spp."),
    array("Torreya spp.", "Torreya spp."),
    array("Elm spp.", "Ulmus spp."),
    array("Blueberry spp.", "Vaccinium spp."),
    array("Viburnum spp.", "Viburnum spp."),
    array("Wisteria spp.", "Wisteria spp."),
    array("Sweet acacia", "Acacia farnesiana"),
    array("Catclaw acacia", "Acacia greggii"),
    array("Trident maple", "Acer buergerianum"),
    array("Hedge maple", "Acer campestre"),
    array("Horned maple", "Acer diabolicum"),
    array("Florida maple", "Acer floridanum"),
    array("Amur maple", "Acer ginnala"),
    array("Rocky mountain maple", "Acer glabrum"),
    array("Bigtooth maple", "Acer grandidentatum"),
    array("Chalk maple", "Acer leucoderme"),
    array("Bigleaf maple", "Acer macrophyllum"),
    array("Boxelder", "Acer negundo"),
    array("Black maple", "Acer nigrum"),
    array("Japanese maple", "Acer palmatum"),
    array("Striped maple", "Acer pensylvanicum"),
    array("Norway maple", "Acer platanoides"),
    array("Red maple", "Acer rubrum"),
    array("Silver maple", "Acer saccharinum"),
    array("Sugar maple", "Acer saccharum"),
    array("Mountain maple", "Acer spicatum"),
    array("Freeman maple", "Acer X freemanii"),
    array("Everglades palm", "Acoelorraphe wrightii"),
    array("California buckeye", "Aesculus californica"),
    array("Yellow buckeye", "Aesculus flava"),
    array("Ohio buckeye", "Aesculus glabra"),
    array("Horse chestnut", "Aesculus hippocastanum"),
    array("Bottlebrush buckeye", "Aesculus parviflora"),
    array("Red buckeye", "Aesculus pavia"),
    array("Painted buckeye", "Aesculus sylvatica"),
    array("Yellow buckeye", "Aesculus flava"),
    array("Tree of heaven", "Ailanthus altissima"),
    array("Mimosa", "Albizia julibrissin"),
    array("European alder", "Alnus glutinosa"),
    array("Arizona alder", "Alnus oblongifolia"),
    array("White alder", "Alnus rhombifolia"),
    array("Red alder", "Alnus rubra"),
    array("Hazel alder", "Alnus serrulata"),
    array("Grey alder", "Alnus incana"),
    array("Serviceberry", "Amelanchier"),
    array("Common serviceberry", "Amelanchier arborea"),
    array("Allegheny serviceberry", "Amelanchier laevis"),
    array("Roundleaf serviceberry", "Amelanchier sanguinea"),
    array("Sea torchwood", "Amyris elemifera"),
    array("Pond-apple  ", "Annona glabra"),
    array("Arizona madrone", "Arbutus arizonica"),
    array("Pacific madrone", "Arbutus menziesii"),
    array("Texas madrone", "Arbutus xalapensis"),
    array("Dwarf pawpaw", "Asimina pygmea"),
    array("Pawpaw", "Asimina triloba"),
    array("Black-mangrove", "Avicennia germinans"),
    array("Eastern baccharis", "Baccharis halimifolia"),
    array("Yellow birch", "Betula alleghaniensis"),
    array("Sweet birch", "Betula lenta"),
    array("White birch", "Betula minor"),
    array("River birch", "Betula nigra"),
    array("Water birch", "Betula occidentalis"),
    array("Paper birch", "Betula papyrifera"),
    array("Gray birch", "Betula populifolia"),
    array("Virginia roundleaf birch", "Betula uber"),
    array("Northwestern paper birch", "Betula x utahensis"),
    array("Gumbo limbo  ", "Bursera simaruba"),
    array("American beautyberry", "Callicarpa americana"),
    array("Incense-cedar", "Calocedrus decurrens"),
    array("Eastern sweetshrub", "Calycanthus floridus"),
    array("American hornbeam", "Carpinus caroliniana"),
    array("Mockernut hickory", "Carya alba"),
    array("Water hickory", "Carya aquatica"),
    array("Southern shagbark hickory", "Carya carolinae-septentrionalis"),
    array("Bitternut hickory", "Carya cordiformis"),
    array("Scrub hickory", "Carya floridana"),
    array("Pignut hickory", "Carya glabra"),
    array("Pecan", "Carya illinoinensis"),
    array("Shellbark hickory", "Carya laciniosa"),
    array("Nutmeg hickory", "Carya myristiciformis"),
    array("Red hickory", "Carya ovalis"),
    array("Shagbark hickory", "Carya ovata"),
    array("Sand hickory", "Carya pallida"),
    array("Black hickory", "Carya texana"),
    array("Mockernut hickory", "Carya tomentosa"),
    array("American chestnut", "Castanea dentata"),
    array("Chinese chestnut", "Castanea mollissima"),
    array("Chinquapin", "Castanea pumila"),
    array("Gray sheoak", "Casuarina glauca"),
    array("Belah", "Casuarina lepidophloia"),
    array("Southern catalpa", "Catalpa bignonioides"),
    array("Northern catalpa", "Catalpa speciosa"),
    array("Oriental bittersweet", "Celastrus orbiculatus"),
    array("Sugarberry", "Celtis laevigata"),
    array("Western hackberry", "Celtis occidentalis"),
    array("Common buttonbush", "Cephalanthus occidentalis"),
    array("Eastern redbud", "Cercis canadensis"),
    array("Curlleaf mountain-mahogany", "Cercocarpus ledifolius"),
    array("Chinese quince", "Chaenomeles sinensis"),
    array("Fragrant wintersweet", "Chimonanthus praecox"),
    array("Giant chinkapin", "Chrysolepis chrysophylla"),
    array("Camphortree", "Cinnamomum camphora"),
    array("Florida fiddlewood", "Citharexylum fruticosum"),
    array("Kentucky yellowwood", "Cladrastis kentukea"),
    array("Tietongue", "Coccoloba diversifolia"),
    array("Florida silver palm", "Coccothrinax argentata"),
    array("Coconut palm  ", "Cocos nucifera"),
    array("Soldierwood", "Colubrina elliptica"),
    array("Bluewood", "Condalia hookeri"),
    array("Buttonwood-mangrove", "Conocarpus erectus"),
    array("Anacahuita", "Cordia boissieri"),
    array("Largeleaf geigertree", "Cordia sebestena"),
    array("Alternate-leaf dogwood", "Cornus alternifolia"),
    array("Silky dogwood", "Cornus amomum"),
    array("Roughleaf dogwood", "Cornus drummondii"),
    array("Flowering dogwood", "Cornus florida"),
    array("Stiff dogwood", "Cornus foemina"),
    array("Kousa dogwood", "Cornus kousa"),
    array("Big-leaf dogwood", "Cornus macrophylla"),
    array("Cornelian cherry", "Cornus mas"),
    array("Pacific dogwood", "Cornus nuttallii"),
    array("Redosier dogwood", "Cornus sericea"),
    array("Grey dogwood", "Cornus racemosa"),
    array("American hazelnut", "Corylus americana"),
    array("Beaked hazel", "Corylus cornuta"),
    array("Smoketree", "Cotinus obovatus"),
    array("Brainerd's hawthorn", "Crataegus brainerdii"),
    array("Pear hawthorn", "Crataegus calpodendron"),
    array("Fireberry hawthorn", "Crataegus chrysocarpa"),
    array("Cockspur hawthorn", "Crataegus crus-galli"),
    array("Broadleaf hawthorn", "Crataegus dilatata"),
    array("Fanleaf hawthorn", "Crataegus flabellata"),
    array("Downy hawthorn", "Crataegus mollis"),
    array("Oneseed hawthorn", "Crataegus monogyna"),
    array("Scarlet hawthorn", "Crataegus pedicellata"),
    array("Washington hawthorn", "Crataegus phaenopyrum"),
    array("Fleshy hawthorn", "Crataegus succulenta"),
    array("Dwarf hawthorn", "Crataegus uniflora"),
    array("Broadleaf hawthorn", "Crataegus coccinioides"),
    array("Carrotwood", "Cupaniopsis anacardioides"),
    array("Swamp titi", "Cyrilla racemiflora"),
    array("Texas persimmon", "Diospyros texana"),
    array("Common persimmon", "Diospyros virginiana"),
    array("Blackbead ebony", "Ebenopsis ebano"),
    array("Oriental paperbush", "Edgeworthia chrysantha"),
    array("Anacua knockaway", "Ehretia anacua"),
    array("Russian olive", "Elaeagnus angustifolia"),
    array("Autumn olive", "Elaeagnus umbellata"),
    array("River redgum", "Eucalyptus camaldulensis"),
    array("Tasmanian bluegum", "Eucalyptus globulus"),
    array("Grand eucalyptus", "Eucalyptus grandis"),
    array("Swampmahogany", "Eucalyptus robusta"),
    array("Red stopper", "Eugenia rhombea"),
    array("Burningbush", "Euonymus alatus"),
    array("European spindletree", "Euonymus europaeus"),
    array("Yeddo euonymous", "Euonymus hamiltonianus"),
    array("Butterbough", "Exothea paniculata"),
    array("American beech", "Fagus grandifolia"),
    array("European beech", "Fagus sylvatica"),
    array("Japanese knotweed", "Fallopia japonica"),
    array("Speckled japanese aralla", "Fatsia japonica"),
    array("Florida strangler fig", "Ficus aurea"),
    array("Wild banyantree", "Ficus citrifolia"),
    array("Florida swampprivet", "Forestiera segregata"),
    array("White ash", "Fraxinus americana"),
    array("Berlandier ash", "Fraxinus berlandieriana"),
    array("Carolina ash", "Fraxinus caroliniana"),
    array("Oregon ash", "Fraxinus latifolia"),
    array("Black ash", "Fraxinus nigra"),
    array("Green ash", "Fraxinus pennsylvanica"),
    array("Pumpkin ash", "Fraxinus profunda"),
    array("Blue ash", "Fraxinus quadrangulata"),
    array("Texas ash", "Fraxinus texensis"),
    array("Velvet ash", "Fraxinus velutina"),
    array("Black huckleberry", "Gaylussacia baccata"),
    array("Ginkgo", "Ginkgo biloba"),
    array("Waterlocust", "Gleditsia aquatica"),
    array("Honeylocust", "Gleditsia triacanthos"),
    array("Loblolly-bay", "Gordonia lasianthus"),
    array("Beeftree", "Guapira discolor"),
    array("Kentucky coffeetree", "Gymnocladus dioicus"),
    array("Carolina silverbell", "Halesia carolina"),
    array("Two-wing silverbell", "Halesia diptera"),
    array("Little silverbell", "Halesia parviflora"),
    array("Witch-hazel", "Hamamelis virginiana"),
    array("Ozark witch hazel", "Hamamelis vernalis"),
    array("Rose of sharon", "Hibiscus syriacus"),
    array("Manchineel", "Hippomane mancinella"),
    array("Raisin", "Hovenia dulcis"),
    array("Oakleaf hydrangea", "Hydrangea quercifolia"),
    array("Possumhaw", "Ilex decidua"),
    array("Inkberry", "Ilex glabra"),
    array("Mountain holly", "Ilex montana"),
    array("Catberry", "Ilex mucronata"),
    array("American holly", "Ilex opaca"),
    array("Winterberry", "Ilex verticillata"),
    array("Yaupon", "Ilex vomitoria"),
    array("Virginia sweetspire", "Itea virginica"),
    array("Southern california black walnut", "Juglans californica"),
    array("Butternut", "Juglans cinerea"),
    array("Northern california black walnut", "Juglans hindsii"),
    array("Arizona walnut", "Juglans major"),
    array("Texas walnut", "Juglans microcarpa"),
    array("Black walnut", "Juglans nigra"),
    array("Mountain laurel", "Kalmia latifolia"),
    array("Castor aralia", "Kalopanax septemlobus"),
    array("Flamegold", "Koelreuteria elegans"),
    array("Golden rain tree", "Koelreuteria paniculata"),
    array("Crapemyrtle", "Lagerstroemia indica"),
    array("White-mangrove", "Laguncularia racemosa"),
    array("Great leucaene", "Leucaena pulverulenta"),
    array("Coastal doghobble", "Leucothoe axillaris"),
    array("Japanese privet", "Ligustrum japonicum"),
    array("Waxyleaf privet", "Ligustrum quihoui"),
    array("Northern spicebush", "Lindera benzoin"),
    array("Sweetgum", "Liquidambar styraciflua"),
    array("Tuliptree", "Liriodendron tulipifera"),
    array("Tanoak", "Lithocarpus densiflorus"),
    array("Pink honeysuckle", "Lonicera hispidula"),
    array("Japanese honeysuckle", "Lonicera japonica"),
    array("Amur honeysuckle", "Lonicera maackii"),
    array("Tatarian honeysuckle", "Lonicera tatarica"),
    array("False tamarind", "Lysiloma latisiliquum"),
    array("Amur maackia", "Maackia amurensis"),
    array("Osage-orange", "Maclura pomifera"),
    array("Cucumbertree", "Magnolia acuminata"),
    array("Fraser's magnolia", "Magnolia fraseri"),
    array("Southern magnolia", "Magnolia grandiflora"),
    array("Bigleaf magnolia", "Magnolia macrophylla"),
    array("Pyramid magnolia", "Magnolia pyramidata"),
    array("Umbrella magnolia", "Magnolia tripetala"),
    array("Sweetbay", "Magnolia virginiana"),
    array("Loebner magnolia", "Magnolia X loebneri"),
    array("Southern crab apple", "Malus angustifolia"),
    array("Siberian crab apple", "Malus baccata"),
    array("Sweet crab apple", "Malus coronaria"),
    array("Oregon crab apple", "Malus fusca"),
    array("Prairie crab apple", "Malus ioensis"),
    array("Toringa crab apple", "Malus sieboldii"),
    array("Mango", "Mangifera indica"),
    array("Melaleuca", "Melaleuca quinquenervia"),
    array("Chinaberry", "Melia azedarach"),
    array("Florida poisontree", "Metopium toxiferum"),
    array("Southern bayberry", "Morella caroliniensis"),
    array("Wax myrtle", "Morella cerifera"),
    array("Red bay", "Morella rubra"),
    array("White mulberry", "Morus alba"),
    array("Texas mulberry", "Morus microphylla"),
    array("Black mulberry", "Morus nigra"),
    array("Red mulberry", "Morus rubra"),
    array("Heavenly bamboo", "Nandina domestica"),
    array("Water tupelo", "Nyssa aquatica"),
    array("Swamp tupelo", "Nyssa biflora"),
    array("Ogeechee tupelo", "Nyssa ogeche"),
    array("Blackgum", "Nyssa sylvatica"),
    array("Desert ironwood", "Olneya tesota"),
    array("Eastern hophornbeam", "Ostrya virginiana"),
    array("Sourwood", "Oxydendrum arboreum"),
    array("Persian ironwood", "Parrotia persica"),
    array("Paulownia  empress-tree", "Paulownia tomentosa"),
    array("Avocado", "Persea americana"),
    array("Redbay", "Persea borbonia"),
    array("Common ninebark", "Physocarpus opulifolius"),
    array("Fishpoison tree", "Piscidia piscipula"),
    array("Water-elm  planertree", "Planera aquatica"),
    array("American sycamore", "Platanus occidentalis"),
    array("California sycamore", "Platanus racemosa"),
    array("Arizona sycamore", "Platanus wrightii"),
    array("Silver poplar", "Populus alba"),
    array("Narrowleaf cottonwood", "Populus angustifolia"),
    array("Balsam poplar", "Populus balsamifera"),
    array("Eastern cottonwood", "Populus deltoides"),
    array("Fremont cottonwood", "Populus fremontii"),
    array("Bigtooth aspen", "Populus grandidentata"),
    array("Swamp cottonwood", "Populus heterophylla"),
    array("Lombardy poplar", "Populus nigra"),
    array("Quaking aspen", "Populus tremuloides"),
    array("Honey mesquite ", "Prosopis glandulosa"),
    array("Screwbean mesquite", "Prosopis pubescens"),
    array("Velvet mesquite", "Prosopis velutina"),
    array("Allegheny plum", "Prunus alleghaniensis"),
    array("American plum", "Prunus americana"),
    array("Chickasaw plum", "Prunus angustifolia"),
    array("Sweet cherry", "Prunus avium"),
    array("Sour cherry", "Prunus cerasus"),
    array("European plum", "Prunus domestica"),
    array("Bitter cherry", "Prunus emarginata"),
    array("Cherry laurel", "Prunus laurocerasus"),
    array("Mahaleb cherry", "Prunus mahaleb"),
    array("Beach plum", "Prunus maritima"),
    array("Japanese apricot", "Prunus mume"),
    array("Canada plum", "Prunus nigra"),
    array("Pin cherry", "Prunus pensylvanica"),
    array("Peach", "Prunus persica"),
    array("Black cherry", "Prunus serotina"),
    array("Chokecherry", "Prunus virginiana"),
    array("Kwanzan cherry", "Prunus serrulata"),
    array("Weeping cherry", "Prunus subhirtella"),
    array("Wafer ash", "Ptelea trifoliata"),
    array("Buffalo nut", "Pyrularia pubera"),
    array("Callery pear", "Pyrus calleryana"),
    array("California live oak", "Quercus agrifolia"),
    array("White oak", "Quercus alba"),
    array("Arizona white oak", "Quercus arizonica"),
    array("Swamp white oak", "Quercus bicolor"),
    array("Buckley oak", "Quercus buckleyi"),
    array("Canyon live oak", "Quercus chrysolepis"),
    array("Scarlet oak", "Quercus coccinea"),
    array("Blue oak", "Quercus douglasii"),
    array("Northern pin oak", "Quercus ellipsoidalis"),
    array("Emory oak", "Quercus emoryi"),
    array("Engelmann oak", "Quercus engelmannii"),
    array("Southern red oak", "Quercus falcata"),
    array("Gambel oak", "Quercus gambelii"),
    array("Oregon white oak", "Quercus garryana"),
    array("Ring-cup oak", "Quercus glauca"),
    array("Chisos oak", "Quercus graciliformis"),
    array("Graves oak", "Quercus gravesii"),
    array("Gray oak", "Quercus grisea"),
    array("Silverleaf oak", "Quercus hypoleucoides"),
    array("Bear oak", "Quercus ilicifolia"),
    array("Shingle oak", "Quercus imbricaria"),
    array("Bluejack oak", "Quercus incana"),
    array("California black oak", "Quercus kelloggii"),
    array("Lacey oak", "Quercus laceyi"),
    array("Turkey oak", "Quercus laevis"),
    array("Laurel oak", "Quercus laurifolia"),
    array("California white oak", "Quercus lobata"),
    array("Overcup oak", "Quercus lyrata"),
    array("Bur oak", "Quercus macrocarpa"),
    array("Dwarf post oak", "Quercus margarettiae"),
    array("Blackjack oak", "Quercus marilandica"),
    array("Swamp chestnut oak", "Quercus michauxii"),
    array("Dwarf live oak", "Quercus minima"),
    array("Chestnut oak", "Quercus montana"),
    array("Chinkapin oak", "Quercus muehlenbergii"),
    array("Water oak", "Quercus nigra"),
    array("Mexican blue oak", "Quercus oblongifolia"),
    array("Oglethorpe oak", "Quercus oglethorpensis"),
    array("Cherrybark oak", "Quercus pagoda"),
    array("Pin oak", "Quercus palustris"),
    array("Willow oak", "Quercus phellos"),
    array("Mexican white oak", "Quercus polymorpha"),
    array("Dwarf chinkapin oak", "Quercus prinoides"),
    array("English oak", "Quercus robur"),
    array("Northern red oak", "Quercus rubra"),
    array("Netleaf oak", "Quercus rugosa"),
    array("Shumard oak", "Quercus shumardii"),
    array("Delta post oak", "Quercus similis"),
    array("Durand oak", "Quercus sinuata"),
    array("Post oak", "Quercus stellata"),
    array("Texas red oak", "Quercus texana"),
    array("Black oak", "Quercus velutina"),
    array("Live oak", "Quercus virginiana"),
    array("Interior live oak", "Quercus wislizeni"),
    array("Common buckthorn", "Rhamnus cathartica"),
    array("Frangula alnus", "Rhamnus frangula"),
    array("American mangrove", "Rhizophora mangle"),
    array("Dwarf azalea", "Rhododendron atlanticum"),
    array("Florida azalea", "Rhododendron austrinum"),
    array("Mountain azalea", "Rhododendron canescens"),
    array("Catawba rhododendron", "Rhododendron catawbiense"),
    array("Piedmont azalea", "Rhododendron flammeum"),
    array("Great rhododendron", "Rhododendron maximum"),
    array("Plumleaf azalea", "Rhododendron prunifolium"),
    array("Jetbead", "Rhodotypos scandens"),
    array("Winged sumac", "Rhus copallinum"),
    array("Smooth sumac", "Rhus glabra"),
    array("Staghorn sumac", "Rhus typhina"),
    array("New mexico locust", "Robinia neomexicana"),
    array("Black locust", "Robinia pseudoacacia"),
    array("Multiflora rose", "Rosa multiflora"),
    array("Wineberry", "Rubus phoenicolasius"),
    array("Mexican palmetto", "Sabal mexicana"),
    array("Cabbage palmetto", "Sabal palmetto"),
    array("White willow", "Salix alba"),
    array("Peachleaf willow", "Salix amygdaloides"),
    array("Weeping willow", "Salix babylonica"),
    array("Bebb willow", "Salix bebbiana"),
    array("Bonpland willow", "Salix bonplandiana"),
    array("Coastal plain willow", "Salix caroliniana"),
    array("Black willow", "Salix nigra"),
    array("Balsam willow", "Salix pyrifolia"),
    array("Scoulers willow", "Salix scouleriana"),
    array("Red elderberry", "Sambucus racemosa"),
    array("Western soapberry", "Sapindus saponaria"),
    array("Sassafras", "Sassafras albidum"),
    array("Octopus tree", "Schefflera actinophylla"),
    array("False mastic", "Sideroxylon foetidissimum"),
    array("Chittamwood", "Sideroxylon lanuginosum"),
    array("White bully", "Sideroxylon salicifolium"),
    array("Paradisetree", "Simarouba glauca"),
    array("Texas sophora", "Sophora affinis"),
    array("American mountain-ash", "Sorbus americana"),
    array("European mountain-ash", "Sorbus aucuparia"),
    array("Northern mountain-ash", "Sorbus decora"),
    array("American bladdernut", "Staphylea trifolia"),
    array("Japanese snowbell", "Styrax japonicus"),
    array("West indian mahogany", "Swietenia mahagoni"),
    array("Sweetleaf", "Symplocos tinctoria"),
    array("Japanese tree lilac", "Syringa reticulata"),
    array("Java plum", "Syzygium cumini"),
    array("Tamarind", "Tamarindus indica"),
    array("Key thatch palm", "Thrinax morrisii"),
    array("Florida thatch palm", "Thrinax radiata"),
    array("American basswood", "Tilia americana"),
    array("Littleleaf linden", "Tilia cordata"),
    array("Common lime", "Tilia X europaea"),
    array("California torreya", "Torreya californica"),
    array("Florida torreya", "Torreya taxifolia"),
    array("Chinese tallowtree", "Triadica sebifera"),
    array("Winged elm", "Ulmus alata"),
    array("American elm", "Ulmus americana"),
    array("Cedar elm", "Ulmus crassifolia"),
    array("Siberian elm", "Ulmus pumila"),
    array("Slippery elm", "Ulmus rubra"),
    array("September elm", "Ulmus serotina"),
    array("Rock elm", "Ulmus thomasii"),
    array("California laurel", "Umbellularia californica"),
    array("Highbush blueberry", "Vaccinium corymbosum"),
    array("Deerberry", "Vaccinium stamineum"),
    array("Tungoil tree", "Vernicia fordii"),
    array("Viburnum", "Viburnum"),
    array("Mapleleaf viburnum", "Viburnum acerifolium"),
    array("Southern arrowwood", "Viburnum dentatum"),
    array("Linden arrowwood", "Viburnum dilatatum"),
    array("Nannyberry", "Viburnum lentago"),
    array("Possumhaw viburnum", "Viburnum nudum"),
    array("European cranberrybush", "Viburnum opulus"),
    array("Japanese snowball", "Viburnum plicatum"),
    array("Blackhaw", "Viburnum prunifolium"),
    array("Rusty blackhaw", "Viburnum rufidulum"),
    array("Canyon grape", "Vitis arizonica"),
    array("Joshua tree", "Yucca brevifolia"),
    array("Japanese zelkova", "Zelkova serrata"),
    array("Fir spp.", "Abies spp.", 1),
    array("White-cedar spp.", "Chamaecyparis spp.", 1),
    array("Cypress spp.", "Cupressus spp.", 1),
    array("Redcedar/juniper spp.", "Juniperus spp.", 1),
    array("Larch spp.", "Larix spp.", 1),
    array("Spruce spp.", "Picea spp.", 1, 1),
    array("Pine spp.", "Pinus spp.", 1),
    array("Douglas-fir spp.", "Pseudotsuga spp.", 1),
    array("Baldcypress spp.", "Taxodium spp.", 1),
    array("Yew spp.", "Taxus spp.", 1),
    array("Thuja spp.", "Thuja spp.", 1),
    array("Hemlock spp.", "Tsuga spp.", 1),
    array("Pacific silver fir", "Abies amabilis", 1),
    array("Balsam fir", "Abies balsamea", 1),
    array("Bristlecone fir", "Abies bracteata", 1),
    array("White fir", "Abies concolor", 1),
    array("Fraser fir", "Abies fraseri", 1),
    array("Grand fir", "Abies grandis", 1),
    array("Subalpine fir", "Abies lasiocarpa", 1),
    array("California red fir", "Abies magnifica", 1),
    array("Noble fir", "Abies procera", 1),
    array("Shasta red fir", "Abies shastensis", 1),
    array("Port-orford-cedar", "Chamaecyparis lawsoniana", 1),
    array("Alaska yellow-cedar", "Chamaecyparis nootkatensis", 1),
    array("Atlantic white-cedar", "Chamaecyparis thyoides", 1),
    array("Arizona cypress", "Cupressus arizonica", 1),
    array("Modoc cypress", "Cupressus bakeri", 1),
    array("Tecate cypress", "Cupressus forbesii", 1),
    array("Macnabs cypress", "Cupressus macnabiana", 1),
    array("Monterey cypress", "Cupressus macrocarpa", 1),
    array("Sargents cypress", "Cupressus sargentii", 1),
    array("Ashe juniper", "Juniperus ashei", 1),
    array("California juniper", "Juniperus californica", 1),
    array("Redberry juniper", "Juniperus coahuilensis", 1),
    array("Alligator juniper", "Juniperus deppeana", 1),
    array("Drooping juniper", "Juniperus flaccida", 1),
    array("Oneseed juniper", "Juniperus monosperma", 1),
    array("Western juniper", "Juniperus occidentalis", 1),
    array("Utah juniper", "Juniperus osteosperma", 1),
    array("Pinchot juniper", "Juniperus pinchotii", 1),
    array("Rocky mountain juniper", "Juniperus scopulorum", 1),
    array("Eastern redcedar", "Juniperus virginiana", 1),
    array("Tamarack", "Larix laricina", 1),
    array("Subalpine larch", "Larix lyallii", 1),
    array("Western larch", "Larix occidentalis", 1),
    array("Norway spruce", "Picea abies", 1),
    array("Brewer spruce", "Picea breweriana", 1),
    array("Engelmann spruce", "Picea engelmannii", 1),
    array("White spruce", "Picea glauca", 1),
    array("Black spruce", "Picea mariana", 1),
    array("Blue spruce", "Picea pungens", 1),
    array("Red spruce", "Picea rubens", 1),
    array("Sitka spruce", "Picea sitchensis", 1),
    array("Whitebark pine", "Pinus albicaulis", 1),
    array("Bristlecone pine", "Pinus aristata", 1),
    array("Arizona pine", "Pinus arizonica", 1),
    array("Knobcone pine", "Pinus attenuata", 1),
    array("Foxtail pine", "Pinus balfouriana", 1),
    array("Jack pine", "Pinus banksiana", 1),
    array("Mexican pinyon pine", "Pinus cembroides", 1),
    array("Sand pine", "Pinus clausa", 1),
    array("Lodgepole pine", "Pinus contorta", 1),
    array("Coulter pine", "Pinus coulteri", 1),
    array("Border pinyon", "Pinus discolor", 1),
    array("Shortleaf pine", "Pinus echinata", 1),
    array("Common pinyon", "Pinus edulis", 1),
    array("Slash pine", "Pinus elliottii", 1),
    array("Apache pine", "Pinus engelmannii", 1),
    array("Limber pine", "Pinus flexilis", 1),
    array("Spruce pine", "Pinus glabra", 1),
    array("Jeffrey pine", "Pinus jeffreyi", 1),
    array("Sugar pine", "Pinus lambertiana", 1),
    array("Chihuahua pine", "Pinus leiophylla", 1),
    array("Great basin bristlecone pine", "Pinus longaeva", 1),
    array("Singleleaf pinyon", "Pinus monophylla", 1),
    array("Western white pine", "Pinus monticola", 1),
    array("Bishop pine", "Pinus muricata", 1),
    array("Austrian pine", "Pinus nigra", 1),
    array("Longleaf pine", "Pinus palustris", 1),
    array("Ponderosa pine", "Pinus ponderosa", 1),
    array("Table mountain pine", "Pinus pungens", 1),
    array("Four-leaf or parry pinyon pine", "Pinus quadrifolia", 1),
    array("Monterey pine", "Pinus radiata", 1),
    array("Papershell pinyon pine", "Pinus remota", 1),
    array("Red pine", "Pinus resinosa", 1),
    array("Pitch pine", "Pinus rigida", 1),
    array("Gray or california foothill pine", "Pinus sabiniana", 1),
    array("Pond pine", "Pinus serotina", 1),
    array("Southwestern white pine ", "Pinus strobiformis", 1),
    array("Eastern white pine", "Pinus strobus", 1),
    array("Scotch pine", "Pinus sylvestris", 1),
    array("Loblolly pine", "Pinus taeda", 1),
    array("Torrey pine", "Pinus torreyana", 1),
    array("Virginia pine", "Pinus virginiana", 1),
    array("Washoe pine", "Pinus washoensis", 1),
    array("Bigcone douglas-fir", "Pseudotsuga macrocarpa", 1),
    array("Douglas-fir", "Pseudotsuga menziesii", 1),
    array("Redwood", "Sequoia sempervirens", 1),
    array("Giant sequoia", "Sequoiadendron giganteum", 1),
    array("Pondcypress", "Taxodium ascendens", 1),
    array("Bald cypress", "Taxodium distichum", 1),
    array("Montezuma baldcypress", "Taxodium mucronatum", 1),
    array("Pacific yew", "Taxus brevifolia", 1),
    array("Florida yew", "Taxus floridana", 1),
    array("Eastern white cedar", "Thuja occidentalis", 1),
    array("Western redcedar", "Thuja plicata", 1),
    array("Eastern hemlock", "Tsuga canadensis", 1),
    array("Carolina hemlock", "Tsuga caroliniana", 1),
    array("Western hemlock", "Tsuga heterophylla", 1),
    array("Mountain hemlock", "Tsuga mertensiana", 1),
    // Added 2025-04
    array("Serviceberry spp.", "Amelanchier spp.", 0),
    array("Heartleaf birch", "Betula cordifolia", 0),
    array("Ginkgo spp.", "Ginkgo spp.", 0),
    array("Halesia tetraptera", "Halesia tetraptera", 0),
    array("Common privet", "Ligustrum vulgare", 0),
    array("Lonicera hispidula var. vacillans", "Lonicera hispidula var. vacillans", 0),
    array("Malus sargentii", "Malus sargentii", 0),
    array("Mountain ash", "Piptocarpha tetrantha", 0),
    array("Pyrus pyrifolia", "Pyrus pyrifolia", 0),
    array("Serviceberry spp.", "Amelanchier spp.", 0),
    array("Acca sellowiana", "Acca sellowiana", 0),
    array("Olea spp.", "Olea spp.", 0),
    array("Osmanthus fragrans", "Osmanthus fragrans", 0),
    array("Illicium spp.", "Illicium spp.", 0),
    array("Magnolia figo", "Magnolia figo", 0),
    array("Asimina spp.", "Asimina spp.", 0),
    array("Carolina laurelcherry", "Prunus caroliniana", 0),
    array("Amelanchier alnifolia", "Amelanchier alnifolia", 0),
    array("Green alder", "Alnus viridis", 0),
    array("Buxus sempervirens", "Buxus sempervirens", 0),
    array("Euonymus japonicus", "Euonymus japonicus", 0),
    array("Nerium oleander", "Nerium oleander", 0),
    array("Viburnum tinus", "Viburnum tinus", 0),
    array("Nothoscordum gracile", "Nothoscordum gracile", 0),
    array("Styphnolobium affine", "Styphnolobium affine", 0),
    array("Yucca rostrata", "Yucca rostrata", 0),
    array("Carolina laurelcherry", "Prunus caroliniana", 0),
    array("Beale's barberry", "Berberis bealei", 0),
    array("Stretchberry", "Forestiera pubescens", 0),
    array("Chinese holly", "Ilex cornuta", 0),
    array("Chinese privet", "Ligustrum sinense", 0),
    array("Golden bamboo", "Phyllostachys aurea", 0),
    array("Japanese spindletree", "Euonymus japonicus", 0),
    array("Common gardenia", "Gardenia volkensii", 0),
    array("Tree privet", "Ligustrum lucidum", 0),
    array("Reeve's meadowsweet", "Spiraea cantoniensis", 0),
    array("Strawberry bush", "Euonymus americanus", 0),
    array("Viburnum rhytidophyllum", "Viburnum rhytidophyllum", 0),
    array("Carolina laurelcherry", "Prunus caroliniana", 0),
    array("Bigleaf snowbell", "Styrax grandifolius", 0),
    array("Punica spp.", "Punica spp.", 0),
    array("Camptotheca", "Camptotheca", 0),
    array("Sweet arrowwood", "Viburnum odoratissimum", 0),
    array("Eriobotrya japonica", "Eriobotrya japonica", 0),
    array("Silverbell", "Halesia", 0),
    array("Pussy willow", "Salix discolor", 0),
    array("Alnus viridis ssp. crispa", "Alnus viridis ssp. crispa", 0),
    array("Rosa acicularis", "Rosa acicularis", 0),
    array("Rubus idaeus", "Rubus idaeus", 0),
    array("Lonicera involucrata", "Lonicera involucrata", 0),
    array("Franklin tree", "Franklinia alatamaha", 0),
    array("Crepe myrtle spp.", "Lagerstroemia spp.", 0),
    array("Prunus salicina", "Prunus salicina", 0),
    array("Tilia tomentosa", "Tilia tomentosa", 0),
    array("Ulmus procera", "Ulmus procera", 0),
    array("Pricklyash", "Zanthoxylum", 0),
    array("Syringa vulgaris", "Syringa vulgaris", 0),
    array("Shining willow", "Salix lucida", 0),
    array("Myrobalan plum", "Prunus cerasifera", 0),
    array("Magnolia kobus", "Magnolia kobus", 0),
    array("Prunus sargentii", "Prunus sargentii", 0),
    array("Amelanchier spp.", "Amelanchier spp.", 0),
    array("Quercus hemisphaerica", "Quercus hemisphaerica", 0),
    array("Prunus umbellata", "Prunus umbellata", 0),
    array("Ilex ambigua", "Ilex ambigua", 0),
    array("Hibiscus coccineus", "Hibiscus coccineus", 0),
    array("Hibiscus moscheutos", "Hibiscus moscheutos", 0),
    array("Witch hazel spp.", "Hamamelidaceae spp.", 0),
    array("Lonicera sempervirens", "Lonicera sempervirens", 0),
    array("Chastetree spp.", "Vitex spp.", 0),
    array("Duranta spp.", "Duranta spp.", 0),
    array("Galphimia glauca", "Galphimia glauca", 0),
    array("Lantana spp.", "Lantana spp.", 0),
    array("Southern red-cedar", "Juniperus virginiana var. silicicola", 1),
    array("Silverberry", "Elaeagnus commutata", 0),
    array("Loropetalum spp.", "Loropetalum spp.", 0),
    array("Chinese elm", "Ulmus parvifolia", 0),
    array("Salvia spp.", "Salvia spp.", 0),
    array("Downy arrowwood", "Viburnum rafinesqueanum", 0),
    array("Downy arrowwood", "Viburnum rafinesqueanum", 0),
    array("Deutzia spp.", "Deutzia spp.", 0),
    array("Muscadine", "Vitis rotundifolia", 0),
    array("Salvia spp.", "Salvia spp.", 0),
    array("Viburnum lantana", "Viburnum lantana", 0),
    array("Pinkshell azalea", "Rhododendron vaseyi", 0),
    array("Clethra alnifolia", "Clethra alnifolia", 0),
    array("Gambel's oak spp.", "Quercus gambelii spp.", 0),
    array("Euonymus spp.", "Euonymus spp.", 0),
    array("Minniebush", "Menziesia pilosa", 0),
    array("Northern bayberry", "Morella pensylvanica", 0),
    array("Coastal sweetpepperbush", "Clethra alnifolia", 0),
    array("Desert olive", "Forestiera pubescens", 0),
    array("Nanking cherry", "Prunus tomentosa", 0),
    array("Allegheny blackberry", "Rubus allegheniensis", 0),
    array("Japanese yew", "Taxus cuspidata", 0),
    array("Star magnolia", "Magnolia stellata", 0),
    array("Oriental arborvitae", "Platycladus orientalis", 0),
    array("Rosa nutkana", "Rosa nutkana", 0),
    array("Western serviceberry", "Amelanchier alnifolia", 0),
    array("Rubus spectabilis", "Rubus spectabilis", 0),
    array("Oemleria cerasiformis", "Oemleria cerasiformis", 0),
    array("Vaccinium parvifolium", "Vaccinium parvifolium", 0),
    array("Rhododendron groenlandicum", "Rhododendron groenlandicum", 0),
    array("Populus trichocarpa", "Populus trichocarpa", 0),
    array("Spiraea douglasii", "Spiraea douglasii", 0),
    array("Acer circinatum", "Acer circinatum", 0),
    array("Wayfaring tree", "Viburnum lantana", 0),
    array("Malus domestica", "Malus domestica", 0),
    array("Aesculus X carnea", "Aesculus X carnea", 0),
    array("Pyrus pyrifolia", "Pyrus pyrifolia", 0),
    array("Ribes spp.", "Ribes spp.", 0),
    array("Hibiscus spp.", "Hibiscus spp.", 0),
    array("Eugenia foetida", "Eugenia foetida", 0),
    array("Quadrella cynophallophora", "Quadrella cynophallophora", 0),
    array("Krugiodendron ferreum", "Krugiodendron ferreum", 0),
    array("Ardisia escallonioides", "Ardisia escallonioides", 0),
    array("Psychotria tenuifolia", "Psychotria tenuifolia", 0),
    array("Eugenia axillaris", "Eugenia axillaris", 0),
    array("Gymnanthes lucida", "Gymnanthes lucida", 0),
    array("Spondias purpurea", "Spondias purpurea", 0),
    array("Randia aculeata", "Randia aculeata", 0),
    array("Elder", "Sambucus nigra", 0)  
    );
}
?>