<?php
function SurveyFlaggingExceptions() {
return array(
"Dwarf pawpaw" => 40,
"Pawpaw" => 40,
"Catalpa" => 40,
"Southern catalpa" => 40,
"Northern catalpa" => 40,
"Umbrella magnolia" => 60,
"Cucumber magnolia" => 40,
"Fraser magnolia" => 60,
"Mountain or fraser magnolia" => 60,
"Yucca rostrata" => 60,
"Cucumbertree" => 40,
"Cabbage palmetto" => 80);}

function SurveyFlaggingCompoundLeaves() {
return array(
"Acer negundo" => 1,
"Boxelder" => 1,
"Buckeye" => 1,
"Ohio buckeye" => 1,
"Aesculus hippocastanum" => 1,
"Aesculus parviflora" => 1,
"Bottlebrush buckeye" => 1,
"Red buckeye" => 1,
"Yellow buckeye" => 1,
"Ailanthus" => 1,
"Hickory" => 1,
"Bitternut hickory" => 1,
"Pignut hickory" => 1,
"Pecan" => 1,
"Shellbark hickory" => 1,
"Nutmeg hickory" => 1,
"Shagbark hickory" => 1,
"Mockernut hickory" => 1,
"White ash" => 1,
"Carolina ash" => 1,
"Black ash" => 1,
"Green ash" => 1,
"Walnut" => 1,
"Black walnut" => 1,
"Sumac" => 1,
"Rhus copallinum" => 1,
"Rhus glabra" => 1,
"Rhus typhina" => 1,
"Black locust" => 1,
"Hickory spp." => 1,
"Walnut spp." => 1,
"Ash spp." => 1,
"Sumac?" => 1,
"Sumac spp." => 1,
"Box elder (acer negundo)" => 1,
"Boxelder maple" => 1,
"Horse chestnut" => 1,
"Staghorn sumac" => 1,
"Winged sumac" => 1,
"Tree of heaven" => 1,
"Smooth sumac" => 1,
"Box elder" => 1,
"Aesculus carnea (x hippocastanum & pavia)" => 1,
"Painted buckeye" => 1);}